### ISSUE TITLE
how to set vault location?

### ISSUE THREAD

**Issue by murphychengdu** [mvavassori/obsidian-web-clipper#10]
how to set " extension options"? Is the "vault name" path? I test settings, it couldn't work.
for example, my vault path is "D:\work\ObsidianLib\tech\", and I want to clip articles to dir "09-inbox" under vault path, how to set "extension options"?

can it be used on android phone?

**Comment by mvavassori** [comment]
The name of your obsidian vault should be `tech` while in the directory input you should put `09-inbox/{title}`.

It can't be used on an android phone.

**Comment by mvavassori** [comment]
The extension doesn't save the page's content to your vault. If you wish to add content to the note you should do it manually. That's its intended usage. If you wish to save full page of content by clicking somewhere, you should probably try some other extension.
