### ISSUE TITLE
Does this work on ChromeOS?

### ISSUE THREAD

**Issue by srustamo** [mvavassori/obsidian-web-clipper#11]
It opens Obsidian window, but nothing is pasted to it.

**Comment by Medullitus** [comment]
It's not working anymore!! :/

**Comment by mvavassori** [comment]
I don't understand how is it not working on Chrome OS. Chrome OS can't open URI links?

**Comment by mvavassori** [comment]
Is this still a problem?

**Comment by srustamo** [comment]
sorry, gave away my Chromebook, can't test.
