### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by dlongm01** [mvavassori/obsidian-web-clipper#12]
Hi ... just added feedback on the Chrome webstore page as follows. Note my suggestion in the final sentence:

"As other reviewers have noted, this clipper works very well. It is simple to use and easily managed. It clips the URL of a page and also allows a note to be added. It's very like Google Keep in style. It does not copy page contents - there are other clippers that do that (and do you really want to fill your writing space with screeds of web content?). For me, when writing something on a specific topic, it's great to have just the links and perhaps a note or two placed directly into an Obsidian vault where I can then follow up. A nice tool.

"Limitation: in its present form you can only assign a vault to save a link via the options. Might be easier/quicker to be able to do this directly in the clipper interface because I sometimes want to put links in different vaults."

**Comment by dlongm01** [comment]
Second thoughts - after consideration there is probably not much to be gained by changing the interface. Going to Options works well enough for me ... maybe, similar to Keep, a dropdown list of assigned Vaults could be useful if I am working across more than one Vault for filing links

As it stands this clipper works well enough for my current use. Good job!

**Comment by Medullitus** [comment]
It's not working here! How did you make it work ??

**Comment by dlongm01** [comment]
Go to Options (via hamburer menu):
(i) Provide the name of the Vault that contains the page you want to send the link to;
(ii) provide the name of the page in that Vault where you want the link to be pasted (create the empty page first).
