### ISSUE TITLE
Not Working Anymore

### ISSUE THREAD

**Issue by Medullitus** [mvavassori/obsidian-web-clipper#13]
Unfortunately the plugin is not working anymore

**Comment by hasantr** [comment]
Yeah, I guess that's true.

**Comment by luminax10** [comment]
it just saves the first word of the title. for example: when i save a page titled "how to do..." it jus saves "how".

**Comment by mvavassori** [comment]
Can you share more about what systems are you using, what options have you chose, if it happens every time or not, and/or other useful information.

**Comment by mvavassori** [comment]
I don't have a machine to test on ChromeOS. The extension just generates URI links that carry the note's information. If ChromeOS isn't able to dispatch URI links to system apps, i'm afraid i can't make it work on my end.
