### ISSUE TITLE
Feature Request: Add URL and timestamp as note properties for Dataview compatibility

### ISSUE THREAD

**Issue by saifsmailbox98** [mvavassori/obsidian-web-clipper#15]
It would be great if the Obsidian Web Clipper could automatically include the timestamp and URL as note properties when clipping content. This enhancement would allow users to easily query and organize their clipped content using Dataview.

### Proposed changes

1. Add two new properties to each clipped note:
   - `url`: The source URL of the clipped content
   - `date`: The local timestamp when the content was clipped

### Use case

This feature would enable users to create powerful Dataview queries to organize and filter their clipped content. For example:

```dataview
table date, url from "bookmarks" where url and date sort date asc
```

This query would display a table of all clipped content in the "bookmarks" folder, sorted by date.

### Benefits

- Improved organization of clipped content
- Enhanced searchability and filtering capabilities
- Better integration with Dataview plugin
- Automatic tracking of when and where content was clipped from

### Implementation details

- The `url` property should be extracted from the current page being clipped
- The `date` property should be set to the local time when the clipping occurs
- These properties should be added to the YAML frontmatter of the created note

### Additional notes

This feature would greatly enhance the utility of the Obsidian Web Clipper for users who rely on Dataview for content organization and retrieval.

For those unfamiliar with Obsidian properties, more information can be found in the official Obsidian documentation:
https://help.obsidian.md/Editing+and+formatting/Properties

**Comment by mvavassori** [comment]
I'm considering adding more data points to notes.

At the moment it's just page title as note title and page link at the top of the note. I'm thinking about adding a new form to the extension options to let users who know what they're doing customize the data added to the note.

Thank you for your feedback.

**Comment by mvavassori** [comment]
For the moment i added the option to edit the note's content formatting. In the future i'll consider adding a way to dynamically change the folder path if enough people find it useful.
Thanks for your suggestion @JOduMonT
