### ISSUE TITLE
🤯 Emoji Usage

### ISSUE THREAD

**Issue by dinandmentink** [mvavassori/obsidian-web-clipper#17]
I really like this plugin. It seems to work more consistent and easier than others out there.

Unfortunately there's one thing I can't get done. I use emoji's in my folders/notes, extensively. And it won't save the folder with an emoji in the title:

![image](https://github.com/mvavassori/obsidian-web-clipper/assets/17289887/52e67d70-95dd-4d8a-933b-f2db207df246)

![image](https://github.com/mvavassori/obsidian-web-clipper/assets/17289887/b3ebe2a9-1e4c-4bc1-993a-2f45f2e0a744)

Addendum: without the emoji it works.

**Comment by mvavassori** [comment]
I added the support for emoji in folder names. It will be added as soon as browser stores accept my update.

![Screenshot from 2024-07-06 19-25-30](https://github.com/mvavassori/obsidian-web-clipper/assets/87538212/c7b047ad-9d6a-4f96-86c5-8789f6640cb3)

**Comment by dinandmentink** [comment]
Thanks for the fix and update!
