### ISSUE TITLE
{date} seems to be off by one

### ISSUE THREAD

**Issue by mediapathic** [mvavassori/obsidian-web-clipper#19]
I've just created a note using the test page, today is 2024-09-06, and the date provided by {date} is 2024-09-07.

I'm assuming this is some kind of time zone issue, pulling the date from somewhere that is incorrect. Dates are hard!

Edit: test file was created 20:53 2024-09-06 on the US West Coast, in case that's useful to know.

**Comment by mvavassori** [comment]
The next update will fix this, it was indeed a problem of time zones. I erroneously used UTC time instead of local date.
Thank you having took the time to open an issue.
