### ISSUE TITLE
No way to add tags

### ISSUE THREAD

**Issue by dmonder** [mvavassori/obsidian-web-clipper#2]
I don't see a way to add tags. It would be most helpful to be able to add tags when saving a web clipping.

**Comment by mvavassori** [comment]
The extension has no access to your Obsidian vault so it can't suggest existing tags like you would do on the desktop app (if that's what you're referring to); however you can manually write tags obviously, like so: 

## Note title
A brief note taken from my web browser.

#Tag1 #Tag2

**Comment by dmonder** [comment]
Of course. Yes, I was hoping there was a way to get the existing tags. Oh well. Thought I would ask. Thanks for responding.

David

http://www.linkedin.com/in/dmonder
“There is no knowing that does not begin with knowing God.” ― John Calvin
