### ISSUE TITLE
Folder With Numbers Is Invalid Format

### ISSUE THREAD

**Issue by ockloh** [mvavassori/obsidian-web-clipper#21]
When I try to set the location for storing my notes to "01 notes/{title}", I get the error: "Invalid folder format. Please use '{title}' or 'Folder Name/{title}' as the folder path." 

I assumed the issue was due to the space, but even when I changed the folder to "01notes", it still showed as invalid.

**Comment by mvavassori** [comment]
Which browser are you using?

**Comment by ockloh** [comment]
Firefox

**Comment by mvavassori** [comment]
I recently added a patch to fix a problem with firefox's emojis, and that apparently broke some functionality. Regex is always fishy to work with... With the new fix you should be able to have numbers.
