### ISSUE TITLE
Doesn’t Work a Quarter of the Time

### ISSUE THREAD

**Issue by ockloh** [mvavassori/obsidian-web-clipper#22]
It will be working fine, then suddenly it does nothing. I can see it is trying to open a new tab, but it never gets sent to Obsidian. If I wait, it eventually works again.

I don't know if it has something to do with multiple Firefox windows open. I have 4 open currently and it was working in half of them, but then it only worked in 1, to 0 working, but now the same 2 that originally worked are fine? The other 2 windows never seem to save the tab, though...

![web clipper](https://github.com/user-attachments/assets/77cf3d4d-57e3-40bd-99b3-ebfaf0a87ec3)

**Comment by mvavassori** [comment]
With just this info i can only suggest to reinstall the extension and make sure to tick the pop up that asks for the permission to open new tabs the first time you save a note.

**Comment by ockloh** [comment]
Reinstalling it fixed it for a day, but now its back to the same issue. It stopped working after I dragged a tabbed out to create an entirely new window for it. I tried reinstalling the extension but it was still broken, restarting Firefox fixed it.
