### ISSUE TITLE
Unable to set path with chinese characters

### ISSUE THREAD

**Issue by hymnly133** [mvavassori/obsidian-web-clipper#3]
Unable to set path with chinese characters,warning "Invalid folder format. Please use '{title}' or 'Folder Name/{title}' as the folder path."

**Comment by mvavassori** [comment]
I changed the folderPattern from:
```
const folderPattern = /^([\w\s().]+\/)*\{title\}$/;
```
to
```
const folderPattern = /^(([\p{L}\p{Script=Hani}\p{Emoji}\s()\-_!@#$%^&()+={}[\];',~][\p{L}\p{Script=Hani}\p{Emoji}\s().\-_!@#$%^&()+={}[\];',~]*\/)*\{title\})$/u;
```
I'm waiting for Chrome to publish the fixed version of the extension, then you'll be able to add Chinese characters.
