### ISSUE TITLE
[Feature Request] Option to modify or include the title within the note

### ISSUE THREAD

**Issue by Savasdotexe** [mvavassori/obsidian-web-clipper#5]
Great extension. Thank you.

I am sure there's other various reasons, but for me I'd like to include the title within the note so that I can later merge and organize if needed.

**Comment by mvavassori** [comment]
I'm glad to hear that you're finding the extension useful.

I understand that having the title automatically included in the note's body can be convenient for certain use cases, and I'll certainly keep it in mind for future updates

For now I'm keeping things simple and not adding new features unless they're super requested. If this becomes a popular request, I will definitely look into adding it as an option in the future.

For the quick fix, you'd have to go old school and copy-paste the title into the note body.

Thank you for taking the time to share your feedback.

**Comment by Savasdotexe** [comment]
Oh I totally understand to keep things simple, wasn't suggesting to do it by default, but what I was rather thinking is in the options to include a section for within the note, similar to what there is with the title which later down the line I imagine there will be requests for further customizability and the ability to structure the output of it.

Thanks again.

**Comment by mvavassori** [comment]
Oh okay, now i get it.

You want to be able to customize the note's content for each note from the options. At the moment the default note content in Obsidian is structured like this:
```
{URL}

{Note's content}
``` 
While you would like to be able to customize this default into something like this:
```
{Title}
{URL}

{Note's content}
```
Did I get it right?

**Comment by Savasdotexe** [comment]
> Oh okay, now i get it.
> 
> You want to be able to customize the note's content for each note from the options. At the moment the default note content in Obsidian is structured like this:
> 
> ```
> {URL}
> 
> {Note's content}
> ```
> 
> While you would like to be able to customize this default into something like this:
> 
> ```
> {Title}
> {URL}
> 
> {Note's content}
> ```
> 
> Did I get it right?

Sorry for the late reply. Yes, that's right.
