### ISSUE TITLE
[Feature request] Ability to use more place holders in the storage URL

### ISSUE THREAD

**Issue by lduperval** [mvavassori/obsidian-web-clipper#6]
Hi,

I wanted to append the clipped articles in the current daily note, but for that, I would need to be able to use the current date. It would be nice if there were a way to do that. Maybe there is and I'm just not seein it. And, of course, I would need to be able to append to an existing note, which is not currently the case

**Comment by mvavassori** [comment]
I can't access the data in your Obsidian Vault, so to me it's not possible to append to an existing note.

The only thing i can do from the browser extension is create a URI link to your Obsidian Vault. It's the link the only source of information. Like so:

`obsidian://new?vault=${encodeURIComponent(
        obsidianVault
      )}&file=${encodeURIComponent(
        finalFolderPath
      )}&content=${encodeURIComponent(newContent)}`
