### ISSUE TITLE
[Feature request] Saving YouTube links with timestamp

### ISSUE THREAD

**Issue by bl03** [mvavassori/obsidian-web-clipper#8]
First of, I'm endlessly thankful for this plug in as it enables me to capture so many ideas that otherwise would've remained plain brain farts.

As stated in the title, it'd be cool to have an option to save a YouTube video link with its timestamp. That would allow us to jump back into a video if needed and have the note + context from the video with minimal to none friction at disposal instantly. 

Cheers

**Comment by mvavassori** [comment]
Hi there,
I will consider adding it if more people need this feature, thank you for the feedback.

**Comment by Medullitus** [comment]
Hello any progress?

**Comment by mvavassori** [comment]
Hi there I was reviewing some issues open, and this seems a very niche use case to make a feature around, the youtube timestamp can be saved by right clicking the video you're watching and clicking on `Copy video URL at current time` from there you can pick 2 different roads: either you manually save the link in the note and remove the page link, or you copy the URL with timestamp in the url address bar and load the page with the correct url and timestamp so you can save the link with the correct timestamp.
